import { FaWifi, FaCoffee, FaBath, FaParking, FaSwimmingPool, FaHotdog, FaStopwatch, FaCocktail } from 'react-icons/fa';
import images from '../assets';

export const roomData = [
  {
    id: 1,
    name: 'Comfort Room',
    description:
      'Perfect for business travelers and couples seeking a peaceful retreat. Our comfort rooms feature modern amenities and tasteful décor, providing everything you need for a restful stay at Phokela Guest House.',
    facilities: [
      { name: 'Free WiFi', icon: FaWifi },
      { name: 'Tea & Coffee', icon: FaCoffee },
      { name: 'Private Bathroom', icon: FaBath },
      { name: 'Secure Parking', icon: FaParking },
      { name: 'Garden Access', icon: FaSwimmingPool },
      { name: 'Breakfast Included', icon: FaHotdog },
      { name: 'Laundry Service', icon: FaStopwatch },
      { name: 'Welcome Refreshments', icon: FaCocktail },
    ],
    size: 25,
    maxPerson: 2,
    price: 850,
    image: images.Room1Img,
    imageLg: images.Room1ImgLg,
  },
  {
    id: 2,
    name: 'Executive Suite',
    description:
      'Spacious and elegantly appointed, our Executive Suites offer enhanced comfort for extended stays or special occasions. Ideal for business executives and families, featuring separate living areas and premium amenities.',
    facilities: [
      { name: 'Free WiFi', icon: FaWifi },
      { name: 'Tea & Coffee Station', icon: FaCoffee },
      { name: 'Ensuite Bathroom', icon: FaBath },
      { name: 'Secure Parking', icon: FaParking },
      { name: 'Garden Views', icon: FaSwimmingPool },
      { name: 'Continental Breakfast', icon: FaHotdog },
      { name: 'Daily Housekeeping', icon: FaStopwatch },
      { name: 'Mini Bar', icon: FaCocktail },
    ],
    size: 45,
    maxPerson: 3,
    price: 1250,
    image: images.Room2Img,
    imageLg: images.Room2ImgLg,
  },
  {
    id: 3,
    name: 'Conference Package',
    description:
      'Professional meeting space with state-of-the-art audio-visual equipment. Perfect for corporate meetings, workshops, and seminars. Includes refreshments, stationery, and technical support for a seamless business experience.',
    facilities: [
      { name: 'High-Speed WiFi', icon: FaWifi },
      { name: 'Tea & Coffee Breaks', icon: FaCoffee },
      { name: 'Private Restrooms', icon: FaBath },
      { name: 'Ample Parking', icon: FaParking },
      { name: 'Breakout Areas', icon: FaSwimmingPool },
      { name: 'Catered Lunch', icon: FaHotdog },
      { name: 'AV Equipment', icon: FaStopwatch },
      { name: 'Welcome Drinks', icon: FaCocktail },
    ],
    size: 60,
    maxPerson: 25,
    price: 2500,
    image: images.Room3Img,
    imageLg: images.Room3ImgLg,
  },
  {
    id: 4,
    name: 'Event Hosting Package',
    description:
      'Make your special occasions memorable with our comprehensive event hosting services. From intimate gatherings to grand celebrations, we provide venue, catering, and coordination for weddings, birthdays, and corporate functions.',
    facilities: [
      { name: 'Event WiFi', icon: FaWifi },
      { name: 'Full Catering', icon: FaCoffee },
      { name: 'Guest Facilities', icon: FaBath },
      { name: 'Valet Parking', icon: FaParking },
      { name: 'Garden Venue', icon: FaSwimmingPool },
      { name: 'Menu Planning', icon: FaHotdog },
      { name: 'Event Coordination', icon: FaStopwatch },
      { name: 'Bar Service', icon: FaCocktail },
    ],
    size: 150,
    maxPerson: 80,
    price: 15000,
    image: images.Room4Img,
    imageLg: images.Room4ImgLg,
  },
  {
    id: 5,
    name: 'Catering Services',
    description:
      'Professional catering for all occasions. Our experienced chefs prepare delicious meals using fresh, local ingredients. Perfect for corporate events, weddings, parties, and daily meal requirements for guest house visitors.',
    facilities: [
      { name: 'Menu Consultation', icon: FaWifi },
      { name: 'Fresh Ingredients', icon: FaCoffee },
      { name: 'Kitchen Facilities', icon: FaBath },
      { name: 'Delivery Service', icon: FaParking },
      { name: 'Outdoor Catering', icon: FaSwimmingPool },
      { name: 'Custom Menus', icon: FaHotdog },
      { name: 'Professional Staff', icon: FaStopwatch },
      { name: 'Beverage Service', icon: FaCocktail },
    ],
    size: 0,
    maxPerson: 100,
    price: 350,
    image: images.Room5Img,
    imageLg: images.Room5ImgLg,
  },
  {
    id: 6,
    name: 'Family Package',
    description:
      'Perfect for families visiting the area or attending events. Our family packages offer comfortable accommodation for multiple guests with special rates for extended stays and family-friendly amenities.',
    facilities: [
      { name: 'Family WiFi', icon: FaWifi },
      { name: 'Family Meals', icon: FaCoffee },
      { name: 'Shared Bathrooms', icon: FaBath },
      { name: 'Family Parking', icon: FaParking },
      { name: 'Play Area', icon: FaSwimmingPool },
      { name: 'Kids Menu', icon: FaHotdog },
      { name: 'Babysitting', icon: FaStopwatch },
      { name: 'Family Games', icon: FaCocktail },
    ],
    size: 65,
    maxPerson: 6,
    price: 1800,
    image: images.Room6Img,
    imageLg: images.Room6ImgLg,
  },
  {
    id: 7,
    name: 'Premium Suite',
    description:
      'Our finest accommodation offering luxury and comfort for discerning guests. Features premium amenities, spacious layout, and personalized service. Ideal for VIP guests, honeymooners, and special occasions.',
    facilities: [
      { name: 'Premium WiFi', icon: FaWifi },
      { name: 'Gourmet Coffee', icon: FaCoffee },
      { name: 'Luxury Bathroom', icon: FaBath },
      { name: 'VIP Parking', icon: FaParking },
      { name: 'Private Terrace', icon: FaSwimmingPool },
      { name: 'Room Service', icon: FaHotdog },
      { name: 'Concierge Service', icon: FaStopwatch },
      { name: 'Premium Bar', icon: FaCocktail },
    ],
    size: 75,
    maxPerson: 4,
    price: 2200,
    image: images.Room7Img,
    imageLg: images.Room7ImgLg,
  },
  {
    id: 8,
    name: 'Corporate Package',
    description:
      'Comprehensive corporate solution including accommodation, meeting facilities, and catering. Perfect for business travelers, corporate retreats, and extended business stays with flexible billing options.',
    facilities: [
      { name: 'Business WiFi', icon: FaWifi },
      { name: 'Meeting Refreshments', icon: FaCoffee },
      { name: 'Executive Facilities', icon: FaBath },
      { name: 'Corporate Parking', icon: FaParking },
      { name: 'Business Lounge', icon: FaSwimmingPool },
      { name: 'Working Lunch', icon: FaHotdog },
      { name: 'Business Services', icon: FaStopwatch },
      { name: 'Networking Area', icon: FaCocktail },
    ],
    size: 40,
    maxPerson: 12,
    price: 3500,
    image: images.Room8Img,
    imageLg: images.Room8ImgLg,
  },
];
